### ISSUE TITLE
`.coordDict` contains coordinates for node ID's not included in the graph

### ISSUE THREAD

**Issue by peterszerzo** [goyalarchit/elm-dagre#3]
I just ran into a situation where I made a graph with only a subset of the available nodes, with the idea that the rest of the nodes (they happen to be completely disconnected) would render below the post-layout graph. When running `Dagre.runLayout [] graph |> .coordDict |> Dict.get someId`, sometimes I get coordinates even if the `someId` was filtered out of the `graph` value (both from nodes and links). I assume these coordinates are useful as intermediate values, but I find they are confusing to be included in the final result. What do you think @goyalarchit?

@goyalarchit I'm continuing to have a great time using the library, thanks so much again for writing and maintaining.

**Comment by goyalarchit** [comment]
@peterszerzo Thank you for your kind words! I'm delighted you found the library helpful. 

About the issue, the `additional IDs` you see in the `coordDict` field are the IDs assigned to the `dummy vertices`, also called `bend/control points`. The coordinates associated with these IDs are used as control points while drawing the graph's edges. These additional node IDs are in the range `[max-node-id-in-original-graph+1, infinity)`. A related question is asked in this [issue](https://github.com/goyalarchit/elm-dagre/issues/2)

- For example, in your case, let the original graph be G(V, E). V = {1,2,3,....28} (set of node-ids), E is any arbitrary set of edges.
- Suppose the node-ids which are non-prime are completely disconnected,
- Then the nodes which are connected V_c = {2,3,5,7,11,13,17,19,23}
- You pass the connected graph G_c (V_c, E) to the `run_layout`.
- It just so happens that the optimal drawing needs five additional dummy vertices for drawing long edges in the graph.
- Based on the current implementation, these additional vertices are assigned node_ids {24,25,26,27,28} (since the max node id was 23).
- You may have a collision while drawing since there are two sets of vertices with the IDs {24..28} (original nodes and dummy nodes from the elm-dagre).
- But these dummy nodes and associated IDs will be helpful in drawing the connected graph and hence are returned in the final result.

I am not sure, but I think due to collision, you need to draw/render the graph in two steps:
1. Connected graph using the final result of run_layout keeping the dummy nodes as control points while drawing edges with control points. _Note: The control points associated with an edge are in the `controlPtsDict`, along with the order of the control points_
2. Disconnected Vertices using the custom logic.

Please let me know if this helps. And in case you were referring to something else with the term `intermediate values`, please share about that too, I would be happy to discuss it further with you.

**Comment by peterszerzo** [comment]
@goyalarchit thanks so much for this detailed explanation, I learned a lot!! I might just remove the dummy vertices in my case myself since I'm doing my own rendering, including the bezier curve build-up of the connectors.

**Comment by goyalarchit** [comment]
@peterszerzo You're welcome! I'm happy to help in any way I can. I have one suggestion which may save you some time and effort: You may want to keep the dummy vertices as those vertices are the least number of vertices required to draw the drawing while also trying to minimize the number of edge crossings as computed by the Sugiyama algorithm. Since you are doing your own rendering, you could use these dummy vertices directly while building the bezier curves or can also generate your own control points by tweaking the coordinates of the dummy vertices.

**Comment by peterszerzo** [comment]
Great suggestion @goyalarchit, unfortunately the bezier curve shape is outside of my control since the logic of it should work both when a Dagre layout is used and when it isn't.
